wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1660473394.116588
    t:
      1:
      - 1
      - 4
      - 41
      - 55
      2:
      - 1
      - 4
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      - 24
      4: 3.6.13
      5: 0.13.1
      8:
      - 5
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: imagewoof
experiment:
  desc: null
  value: Simultaneous
gpu:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0001
model:
  desc: null
  value: resnet26
num_classes:
  desc: null
  value: 10
num_epochs:
  desc: null
  value: 100
percentage:
  desc: null
  value: null
seed:
  desc: null
  value: 0
stage:
  desc: null
  value: 0
